# Generated by Django 4.2.5 on 2023-09-11 21:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chatapp", "0002_rename_user_chatuser"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatuser",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"managed": True},
        ),
        migrations.AlterModelTable(
            name="chatuser",
            table="chatapp_chatuser",
        ),
        migrations.AlterModelTable(
            name="message",
            table="chatapp_message",
        ),
    ]
