# Generated by Django 4.2.5 on 2023-09-11 21:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chatapp", "0003_alter_chatuser_options_alter_message_options_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="chatuser",
            table="chatapp_user",
        ),
    ]
